version: "0"

services:
  restapitest:
    image: mysql
    ports:
      - 3308:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: restapi
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
